name: Zip Files on Tag

on:
  push:
    tags:
      - "*"  # Triggers on any tag

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Tag Name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Prepare files for zipping
        run: |
          mkdir -p craimasjiens-mod-pack
          cp -r "Craimasjien's Mod Pack.modinfo" text/ ui/
       
      - name: Create ZIP Archive
        run: |
          zip -r craimasjiens-civ-vii-mod-pack-${TAG_NAME}.zip craimasjiens-mod-pack/

      - name: Upload ZIP as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: craimasjiens-civ-vii-mod-pack-${{ env.TAG_NAME }}
          path: craimasjiens-civ-vii-mod-pack-${{ env.TAG_NAME }}.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          body_path: RELEASE_NOTES.md
          files: craimasjiens-civ-vii-mod-pack-${{ env.TAG_NAME }}.zip